development:
  adapter: postgresql
  database: tumblr_clone_development
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: tumblr_clone_test
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: tumblr_clone_production
  pool: 5
  timeout: 5000